version: 2
updates: 
  # Enable version updates for nuget 
  - package-ecosystem: "nuget"
    directory: "src/"
    interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    interval: "daily"
