version: 2
updates:
  # Enable version updates for NuGet dependencies in src and tests.
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/src"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "23:30"
      timezone: "America/Toronto"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
